In [6]:
df=pd.read_csv(r'C:\Users\hp\Documents\Titanic.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
import pandas as pd

In [9]:
df['Age']=df['Age'].fillna(df['Age'].median())

In [12]:
df['Embarked']=df['Embarked'].fillna(df['Embarked'].mode())

In [15]:
from sklearn.preprocessing import LabelEncoder

In [18]:
df['Embarked']=LabelEncoder().fit_transform(df['Embarked'])

In [21]:
df['Sex']=LabelEncoder().fit_transform(df['Sex'])

In [24]:
df.drop(['Name','Ticket','Cabin'],axis=1)

     PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0              1         0       3    1  22.0      1      0   7.2500         2
1              2         1       1    0  38.0      1      0  71.2833         0
2              3         1       3    0  26.0      0      0   7.9250         2
3              4         1       1    0  35.0      1      0  53.1000         2
4              5         0       3    1  35.0      0      0   8.0500         2
..           ...       ...     ...  ...   ...    ...    ...      ...       ...
886          887         0       2    1  27.0      0      0  13.0000         2
887          888         1       1    0  19.0      0      0  30.0000         2
888          889         0       3    0  28.0      1      2  23.4500         2
889          890         1       1    1  26.0      0      0  30.0000         0
890          891         0       3    1  32.0      0      0   7.7500         1

[891 rows x 9 columns]

In [28]:
x=df[['PassengerId','Pclass','Sex','Age','SibSp','Parch','Fare','Embarked']]

In [31]:
y=df[['Survived']]
y.head(2)

   Survived
0         0
1         1

In [39]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.3,random_state=42)

In [37]:
from sklearn.model_selection import train_test_split

In [45]:
x_train

     PassengerId  Pclass  Sex   Age  SibSp  Parch      Fare  Embarked
445          446       1    1   4.0      0      2   81.8583         2
650          651       3    1  28.0      0      0    7.8958         2
172          173       3    0   1.0      1      1   11.1333         2
450          451       2    1  36.0      1      2   27.7500         2
314          315       2    1  43.0      1      1   26.2500         2
..           ...     ...  ...   ...    ...    ...       ...       ...
106          107       3    0  21.0      0      0    7.6500         2
270          271       1    1  28.0      0      0   31.0000         2
860          861       3    1  41.0      2      0   14.1083         2
435          436       1    0  14.0      1      2  120.0000         2
102          103       1    1  21.0      0      1   77.2875         2

[623 rows x 8 columns]

In [47]:
x_test

     PassengerId  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
709          710       3    1  28.0      1      1  15.2458         0
439          440       2    1  31.0      0      0  10.5000         2
840          841       3    1  20.0      0      0   7.9250         2
720          721       2    0   6.0      0      1  33.0000         2
39            40       3    0  14.0      1      0  11.2417         0
..           ...     ...  ...   ...    ...    ...      ...       ...
821          822       3    1  27.0      0      0   8.6625         2
633          634       1    1  28.0      0      0   0.0000         2
456          457       1    1  65.0      0      0  26.5500         2
500          501       3    1  17.0      0      0   8.6625         2
430          431       1    1  28.0      0      0  26.5500         2

[268 rows x 8 columns]

In [49]:
y_train

     Survived
445         1
650         0
172         1
450         0
314         0
..        ...
106         1
270         0
860         0
435         1
102         0

[623 rows x 1 columns]

In [51]:
y_test

     Survived
709         1
439         0
840         0
720         1
39          1
..        ...
821         1
633         0
456         0
500         0
430         1

[268 rows x 1 columns]

In [173]:
from sklearn.linear_model import LogisticRegression

In [117]:
model=LogisticRegression(max_iter=1000)
model.fit(x_train,y_train)

LogisticRegression(max_iter=1000)

In [113]:
import warnings

In [115]:
warnings.filterwarnings('ignore')

In [60]:
y_pred=model.predict(x_test)
y_pred

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0], dtype=int64)

In [63]:
y_pred1=model.predict(x_train)
y_pred1

array([1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0], dtype=int64)

In [122]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [81]:
accuracy_score(y_pred,y_test)

0.8097014925373134

In [238]:
accuracy_score(y_pred1,y_train)

0.48366511096294884

In [107]:
confusion_matrix(y_pred,y_test)

array([[136,  30],
       [ 21,  81]], dtype=int64)

confusion matrix elements
1. True Positive (TP):
   * These are cases where the model correctly predicted the positive class.
2. False Positive (FP):
   * These are cases where the model incorrectly predicted the positive class.
3. True Negative (TN):
   * These are cases where the model correctly predicted the negative class.
4. False Negative (FN):
   * These are cases where the model incorrectly predicted the negative class.

In [109]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.87      0.82      0.84       166
           1       0.73      0.79      0.76       102

    accuracy                           0.81       268
   macro avg       0.80      0.81      0.80       268
weighted avg       0.81      0.81      0.81       268

In [111]:
y_test.value_counts()

Survived
0           157
1           111
Name: count, dtype: int64

1. over fit:
   * train-85%
   * test-70%
2. underfit
   * train-70%
   * test-70%
3. generalized
   * train-85%
   * test-85%

In [131]:
import pandas as pd

In [181]:
df=pd.read_csv(r"C:\Users\hp\Documents\HR_comma_sep.csv")
df

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.72,0.87,5,223,5,0,1,0,sales,low
4,0.37,0.52,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...,...
14994,0.40,0.57,2,151,3,0,1,0,support,low
14995,0.37,0.48,2,160,3,0,1,0,support,low
14996,0.37,0.53,2,143,3,0,1,0,support,low
14997,0.11,0.96,6,280,4,0,1,0,support,low
14998,0.37,0.52,2,158,3,0,1,0,support,low

In [183]:
df.isnull().sum()

satisfaction_level       0
last_evaluation          0
number_project           0
average_montly_hours     0
time_spend_company       0
Work_accident            0
left                     0
promotion_last_5years    0
Department               0
salary                   0
dtype: int64

In [185]:
from sklearn.preprocessing import LabelEncoder

In [187]:
df['salary']=LabelEncoder().fit_transform(df['salary'])
df

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary
0,0.38,0.53,2,157,3,0,1,0,sales,1
1,0.80,0.86,5,262,6,0,1,0,sales,2
2,0.11,0.88,7,272,4,0,1,0,sales,2
3,0.72,0.87,5,223,5,0,1,0,sales,1
4,0.37,0.52,2,159,3,0,1,0,sales,1
...,...,...,...,...,...,...,...,...,...,...
14994,0.40,0.57,2,151,3,0,1,0,support,1
14995,0.37,0.48,2,160,3,0,1,0,support,1
14996,0.37,0.53,2,143,3,0,1,0,support,1
14997,0.11,0.96,6,280,4,0,1,0,support,1
14998,0.37,0.52,2,158,3,0,1,0,support,1

In [189]:
df['Department']=LabelEncoder().fit_transform(df['Department'])

In [191]:
x=df[['satisfaction_level','average_montly_hours','number_project','time_spend_company','Department']]

In [193]:
y=df[['salary']]

In [195]:
from sklearn.model_selection import train_test_split

In [197]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.3,random_state=42)

In [199]:
x_train

,satisfaction_level,average_montly_hours,number_project,time_spend_company,Department
12602,0.10,250,7,4,6
4889,0.57,154,4,3,4
1572,0.39,154,2,3,9
13375,0.91,132,4,4,0
879,0.82,263,5,5,9
...,...,...,...,...,...
5191,0.52,246,4,3,8
13418,0.49,233,4,7,7
5390,0.66,249,5,2,8
860,0.79,218,4,5,7
7270,0.98,219,2,4,7

In [201]:
x_test

,satisfaction_level,average_montly_hours,number_project,time_spend_company,Department
6723,0.65,226,5,2,5
6473,0.88,166,3,2,0
4679,0.69,214,3,2,7
862,0.41,154,2,3,7
7286,0.87,254,5,2,3
...,...,...,...,...,...
13388,0.85,260,4,3,6
10463,0.21,249,2,3,5
5331,0.78,156,3,3,6
7499,0.93,238,5,2,7
11796,0.64,246,3,2,5

In [203]:
y_train

       salary
12602       1
4889        2
1572        1
13375       2
879         2
...       ...
5191        1
13418       2
5390        2
860         1
7270        1

[10499 rows x 1 columns]

In [205]:
y_test

       salary
6723        2
6473        1
4679        1
862         1
7286        1
...       ...
13388       2
10463       1
5331        1
7499        2
11796       0

[4500 rows x 1 columns]

In [207]:
from sklearn.linear_model import LogisticRegression

In [209]:
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [228]:
y_pred=model.predict(x_test)
y_pred

array([1, 2, 1, ..., 2, 1, 1])

In [230]:
y_pred1=model.predict(x_train)
y_pred1

array([1, 1, 1, ..., 1, 2, 2])

In [234]:
accuracy_score(y_pred1,y_train)

0.48366511096294884

In [236]:
accuracy_score(y_pred,y_test)

0.48333333333333334